FROM python:3.11-slim

WORKDIR /app
COPY requirements.api.txt /app/
RUN pip install --no-cache-dir -r requirements.api.txt

COPY src /app/src
COPY api /app/api
ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080"]
